builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/docsite
  goarch:
  - amd64
archives:
- id: tarball
  format: tar.gz
- id: bin 
  format: binary
  wrap_in_directory: false
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
